version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: agenticrag-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  chroma:
    image: chromadb/chroma:latest
    container_name: agenticrag-chroma
    ports:
      - "8001:8000"
    volumes:
      - chroma_data:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma
      - ANONYMIZED_TELEMETRY=FALSE

  api:
    build: .
    container_name: agenticrag-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379
      - CHROMA_HOST=chroma
      - CHROMA_PORT=8000
    volumes:
      - ./src:/app/src
      - ./data:/app/data
    depends_on:
      redis:
        condition: service_healthy
      chroma:
        condition: service_started
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  redis_data:
  chroma_data: